### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([45, 43, 87, 55, 49, 79, 75, 49, 18, 90,  2, 38, 75, 28, 48])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 6, 48, 80, 48],
       [94, 28, 67, 61],
       [80, 60, 83, 69],
       [45, 87, 91, 33],
       [67, 21,  1, 98],
       [43, 28, 83, 19]])

In [4]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [ 2 18 28 38 43 45 48 49 49 55 75 75 79 87 90]
Sorted order : [90 87 79 75 75 55 49 49 48 45 43 38 28 18  2]


In [5]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[ 6 48 80 48]
 [94 28 67 61]
 [80 60 83 69]
 [45 87 91 33]
 [67 21  1 98]
 [43 28 83 19]]

column-wise sort :
[[ 6 21  1 19]
 [43 28 67 33]
 [45 28 80 48]
 [67 48 83 61]
 [80 60 83 69]
 [94 87 91 98]]

row-wise sort :
[[ 6 48 48 80]
 [28 61 67 94]
 [60 69 80 83]
 [33 45 87 91]
 [ 1 21 67 98]
 [19 28 43 83]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[ 45  43  87  55  49  79  75  49  18  90   2  38  75  28  48 200]
[[ 6. 48. 80. 48.  1.]
 [94. 28. 67. 61.  1.]
 [80. 60. 83. 69.  1.]
 [45. 87. 91. 33.  1.]
 [67. 21.  1. 98.  1.]
 [43. 28. 83. 19.  1.]]


**np.concatenate:**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


**np.unique :**
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
- Ex.Imagine 1 student register for multiple courses , but we want those user they purches the course so it Uueful to identify the unique users from course 
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [10]:
# Ex
e = np.array([1,2,3,3,4,4,5,5,6,6])
print("E :")
print(e)
