### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([83, 45, 36, 91, 47, 40, 17, 37, 60, 41, 96, 56, 68, 20, 10])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[75, 52, 18, 22],
       [46, 46, 22, 42],
       [81, 45, 99, 40],
       [85, 24, 93, 57],
       [53, 81, 29, 89],
       [44, 30, 75, 26]])

In [22]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [10 17 20 36 37 40 41 45 47 56 60 68 83 91 96]
Sorted order : [96 91 83 68 60 56 47 45 41 40 37 36 20 17 10]


In [61]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[75 52 18 22]
 [46 46 22 42]
 [81 45 99 40]
 [85 24 93 57]
 [53 81 29 89]
 [44 30 75 26]]

column-wise sort :
[[44 24 18 22]
 [46 30 22 26]
 [53 45 29 40]
 [75 46 75 42]
 [81 52 93 57]
 [85 81 99 89]]

row-wise sort :
[[18 22 52 75]
 [22 42 46 46]
 [40 45 81 99]
 [24 57 85 93]
 [29 53 81 89]
 [26 30 44 75]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [47]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[ 83  45  36  91  47  40  17  37  60  41  96  56  68  20  10 200]
[[75. 52. 18. 22.  1.]
 [46. 46. 22. 42.  1.]
 [81. 45. 99. 40.  1.]
 [85. 24. 93. 57.  1.]
 [53. 81. 29. 89.  1.]
 [44. 30. 75. 26.  1.]]


**np.concatenate**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [49]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [58]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [60]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
