### SESSION 13 - NumPy Fundamentals
#### What is numpy?
- NumPy is the fundamental package for scientific computing in Python. 
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

#### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### Creating Numpy Arrays :
- There are 2 ways to importing the numpy module :
    - **`import numpy as np`**
    - **`from numpy import *`**

In [4]:
import numpy as np
# it is vector
a = np.array([1,2,3,4])
print('a :',a)
print('type of a :',type(a))

a : [1 2 3 4]
type of a : <class 'numpy.ndarray'>


#### Creating a 2D and 3D numpy arrays:

In [8]:
from numpy import *
# 2D array (it is matrix)
b = array([[1,2,3],[4,5,6]])
print('2D:',b)

2D: [[1 2 3]
 [4 5 6]]


In [11]:
# 3D array (it is tensor)
c = array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(c)

[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


#### Creating a numpy with different `dtype`:

In [14]:
f = array([1,2,3,4] , dtype=float)
c = array([1,2,3,4] , dtype=complex)
tf = array([1,2,0,4] , dtype=bool) # non integer value consider as True
print('float :',f)
print('complex :',c)
print('boolean :',tf)

float : [1. 2. 3. 4.]
complex : [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
boolean : [ True  True False  True]
