**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [14]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [15]:
def nullVector():
    arr = np.nan * np.zeros(10, dtype=int)
    arr[5] = 1
    return arr
nullVector()

array([nan, nan, nan, nan, nan,  1., nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [16]:
a, b = map(int, input('Enter two numbers').split())
arr = np.random.random((a, b))
print(arr)
print('avg of array:',arr.mean())

Enter two numbers1 5
[[0.91921685 0.8204693  0.21907953 0.35595799 0.56997721]]
avg of array: 0.5769401762471074


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [17]:
def borderFun(a, b):
    arr = np.ones((a, b), dtype=int)
    arr[1:3, 1:3] = 0
    return arr
print(borderFun(4, 4))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [18]:
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [19]:
print(np.eye(3))
print(np.identity(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [20]:
arr = np.zeros((5, 5))
arr += np.arange(5)
print(arr)


# 2nd 
#a = np.tile(np.arange(5), (5, 1))

# 3rd
#a1 = np.zeros((5, 5))
#for i in range(5):
#   a1[i] = np.arange(5)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [21]:
vector = np.random.randint(1, 100, (10, 2))
point = np.array([2,3]) 
print(vector)
np.sqrt(np.sum((vector-point)**2, axis=1)).astype(int)

[[34 71]
 [96 69]
 [94 39]
 [53 41]
 [50 71]
 [38  1]
 [30 97]
 [39 87]
 [53  7]
 [83  7]]


array([ 75, 114,  98,  63,  83,  36,  98,  91,  51,  81])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [4]:
nums = input().strip().split()
print(np.array(nums[::-1], dtype=np.float32))

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [23]:
print('elements_count :',np.array([]).size)
print('elements_count :',np.array([1, 2]).size)

elements_count : 0
elements_count : 2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [24]:
def softMaxFun(arr):
    if type(arr) != np.ndarray:
        raise TypeError('Required numpy Array')
    elif arr.ndim > 1:
        raise TypeError('Requires 1D array')
        
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

Input = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
softMaxFun(Input)      

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [25]:
def verticalStack(*arrays):
    for i in arrays: 
        if type(i) != np.ndarray:
            raise TypeError('Required numpy Array')
    output = np.vstack((arrays))
    return output

a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])

verticalStack(a, b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [26]:
import numpy as np
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError

    starting = np.datetime64(start)
    ending = np.datetime64(end)
    date_range = np.arange(starting, ending + np.timedelta64(1, 'D'), np.timedelta64(1, 'D'))
    return date_range

date_array(start = '2020-11-01', end = '2020-11-30')

array(['2020-11-01', '2020-11-02', '2020-11-03', '2020-11-04',
       '2020-11-05', '2020-11-06', '2020-11-07', '2020-11-08',
       '2020-11-09', '2020-11-10', '2020-11-11', '2020-11-12',
       '2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16',
       '2020-11-17', '2020-11-18', '2020-11-19', '2020-11-20',
       '2020-11-21', '2020-11-22', '2020-11-23', '2020-11-24',
       '2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

In [27]:
import numpy as np
def date_array(start:str, end:str):
    if type(start) != str or type(end) != str:
        raise TypeError 
        
    total_days_of_months = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}
    
    end = end.split('-')
    end_last = int(end[-1]) + 1
    
    if total_days_of_months[end[-2]] < end_last:
        days_diff = end_last - total_days_of_months[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff < 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month < 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = '-'.join(end)
    return np.arange(start, end, dtype='datetime64[D]')

date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [28]:
matrix = np.arange(20).reshape(5, 4)
print(matrix)
# The keepdims=True argument ensures that the calculated mean is retained as a column vector, 
# allowing it to be broadcasted across the rows during subtraction.
res = matrix - matrix.mean(axis=1, keepdims=True)
print('Result :',res)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Result : [[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [29]:
arr = np.arange(9).reshape(3, 3)
print('Before :')
print(arr)
arr[:,[0, 2, 1]] = arr[:, [0, 1, 2]]
print('After :')
print(arr)

Before :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After :
[[0 2 1]
 [3 5 4]
 [6 8 7]]


### `Q-16:` Replace odd elements in arrays with -1.

In [30]:
arr = np.arange(10)
print(arr)
arr[arr%2== 1] = -1
print('result:',arr)

[0 1 2 3 4 5 6 7 8 9]
result: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [31]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
print('Result ->',a)

Result -> [6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [32]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3551, 2882, 7589, 4920,  796],
       [6644, 7531, 4773, 2176, 6149],
       [  20, 4531, 8606,  655, 5637],
       [2783,  330, 3311,  629, 7544],
       [7732, 6972, 7205,  571, 3120],
       [2192, 3500,  469, 3676, 8231],
       [9287, 4187, 5884, 3950, 5055],
       [8661,  299, 3643, 3403,  246]])

In [33]:
# Fetch Every alternate column of the array
print(arr1[:, ::2])

[[3551 7589  796]
 [6644 4773 6149]
 [  20 8606 5637]
 [2783 3311 7544]
 [7732 7205 3120]
 [2192  469 8231]
 [9287 5884 5055]
 [8661 3643  246]]


In [34]:
# Normalise the given array
x_normalied = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
print(x_normalied)

[[0.38102946 0.30883781 0.81676918 0.52875796 0.083738  ]
 [0.71479443 0.81051041 0.51289522 0.2326535  0.66137909]
 [0.         0.48678105 0.92651343 0.06852272 0.60612928]
 [0.29815474 0.03345203 0.35513111 0.06571706 0.81191324]
 [0.83220028 0.75018884 0.77533182 0.05945829 0.33452034]
 [0.23438006 0.37552606 0.04845149 0.39451818 0.88604726]
 [1.         0.44966008 0.63278299 0.42408546 0.54332578]
 [0.93244847 0.03010683 0.39095716 0.36505881 0.02438761]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [35]:
import numpy as np

def nthMax(arr, n):
    if n>len(arr):
        raise IndexError('n is way out of limit')
    arr.sort()
    return arr[-n]
nthMax(np.array([12,34,40,7,1,0]),2)

34

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [39]:
a = np.array([1,2,3])
np.hstack([np.repeat(a,3), np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])