### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([28, 34, 69, 39, 29, 29, 36, 28, 60, 49, 43, 48, 81, 86, 19])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 26,  5, 32],
       [71, 80, 14, 30],
       [58, 36, 97, 10],
       [85,  4, 65, 96],
       [54, 23, 85, 16],
       [13,  3,  9, 48]])

In [4]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [19 28 28 29 29 34 36 39 43 48 49 60 69 81 86]
Sorted order : [86 81 69 60 49 48 43 39 36 34 29 29 28 28 19]


In [5]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[22 26  5 32]
 [71 80 14 30]
 [58 36 97 10]
 [85  4 65 96]
 [54 23 85 16]
 [13  3  9 48]]

column-wise sort :
[[13  3  5 10]
 [22  4  9 16]
 [54 23 14 30]
 [58 26 65 32]
 [71 36 85 48]
 [85 80 97 96]]

row-wise sort :
[[ 5 22 26 32]
 [14 30 71 80]
 [10 36 58 97]
 [ 4 65 85 96]
 [16 23 54 85]
 [ 3  9 13 48]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[ 28  34  69  39  29  29  36  28  60  49  43  48  81  86  19 200]
[[22. 26.  5. 32.  1.]
 [71. 80. 14. 30.  1.]
 [58. 36. 97. 10.  1.]
 [85.  4. 65. 96.  1.]
 [54. 23. 85. 16.  1.]
 [13.  3.  9. 48.  1.]]


**np.concatenate:**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


**np.unique :**
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
- Ex.Imagine 1 student register for multiple courses , but we want those user they purches the course so it useful to identify the unique users from course 
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [10]:
# Ex
e = np.array([1,2,3,3,4,4,5,5,6,6])
print("E :",e)
print('Unique Values :',np.unique(e))

E : [1 2 3 3 4 4 5 5 6 6]
Unique Values : [1 2 3 4 5 6]


**np.expand_dims :**
- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.
- means 1D to 2D convertion or 3d to 4D conversion.
- https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [11]:
print('E:',e)
print('2D :',np.expand_dims(e,axis=0)) # axis 0 is row
print(np.expand_dims(e,axis=0).shape)

E: [1 2 3 3 4 4 5 5 6 6]
2D : [[1 2 3 3 4 4 5 5 6 6]]
(1, 10)


In [12]:
print(np.expand_dims(e,axis=1)) # axis 1 is col
print(np.expand_dims(e,axis=1).shape)

[[1]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]]
(10, 1)


**np.where :**
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [13]:
print(e)
# Ex.find all indices with value greater than 4
print(np.where(e>4))

[1 2 3 3 4 4 5 5 6 6]
(array([6, 7, 8, 9], dtype=int64),)


In [14]:
# Ex.replace all values < 4 with 0
print(np.where(e<4, 0, e))

[0 0 0 0 4 4 5 5 6 6]


**np.argmax :**
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [15]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [16]:
print(np.argmax(e))

8


In [17]:
# 2D 
print(b)

[[22 26  5 32]
 [71 80 14 30]
 [58 36 97 10]
 [85  4 65 96]
 [54 23 85 16]
 [13  3  9 48]]


In [18]:
print(np.argmax(b, axis=0)) # col = 0

[3 1 2 3]


In [19]:
print(np.argmax(b, axis=1)) # row = 1

[3 1 2 3 2 3]


**np.argmin :**
- give the min number index

In [20]:
print(e)
print(np.argmin(e))

[1 2 3 3 4 4 5 5 6 6]
0


In [21]:
print(np.argmin(b, axis=0))

[5 5 0 2]


In [22]:
print(np.argmin(b, axis=1))

[2 2 3 1 3 1]


**np.cumsum :**
- numpy.cumsum() function is used when we want to compute the **cumulative sum of array elements over a given axis.**
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [23]:
# Ex.1D
print(a)
print('cumilative sum : ',np.cumsum(a))

[28 34 69 39 29 29 36 28 60 49 43 48 81 86 19]
cumilative sum :  [ 28  62 131 170 199 228 264 292 352 401 444 492 573 659 678]


In [24]:
# Ex.2D
print(b)

[[22 26  5 32]
 [71 80 14 30]
 [58 36 97 10]
 [85  4 65 96]
 [54 23 85 16]
 [13  3  9 48]]


In [25]:
print(np.cumsum(b))

[ 22  48  53  85 156 236 250 280 338 374 471 481 566 570 635 731 785 808
 893 909 922 925 934 982]


In [26]:
print(np.cumsum(b,axis=0)) # 1 = row

[[ 22  26   5  32]
 [ 93 106  19  62]
 [151 142 116  72]
 [236 146 181 168]
 [290 169 266 184]
 [303 172 275 232]]


In [27]:
print(np.cumsum(b,axis=1)) # 0 = col

[[ 22  48  53  85]
 [ 71 151 165 195]
 [ 58  94 191 201]
 [ 85  89 154 250]
 [ 54  77 162 178]
 [ 13  16  25  73]]


**np.cumprod :**
- numpy.cumprod() function is used multiplication

In [28]:
print(e)
print(np.cumprod(e))

[1 2 3 3 4 4 5 5 6 6]
[     1      2      6     18     72    288   1440   7200  43200 259200]


In [29]:
print(np.cumprod(b))

[         22         572        2860       91520     6497920   519833600
 -1312264192  -713220096  1582907392  1150091264  -110297088 -1102970880
   736755712 -1347944448 -1717043200 -1627389952 -1979711488  1711276032
  -570425344  -536870912  1610612736   536870912   536870912           0]


**np.percentile :**
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
- **formula :** p = (n/N)*100
    - p : percentile
    - n : Number of values fall under(below) 'x' 
    - N : Total count of population

In [30]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [31]:
print(np.percentile(e,0))
print(np.percentile(e,50))
print(np.percentile(e,100))

1.0
4.0
6.0


**np.histogram:**
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution for the graphical form.
- https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [32]:
#Ex.
ee = np.array([11,53,28,50,38,37,94,92,5,30,68,9,78,2,21])
print(ee)

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]


In [33]:
print(np.histogram(ee,bins=[0,10,20,30,40,50,60,70,80,90,100]))

(array([3, 1, 2, 3, 0, 2, 1, 1, 0, 2], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


**np.corrcoef :**
- Return Pearson product-moment correlation coefficients.
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [34]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


**np.isin :**
- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.
- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [35]:
print("ARR :",ee)
i = [10,20,30,40,5,0,11,78,90,65]
print('ITEMS :',i)
result = np.isin(ee,i)
print('Simliar Items :',ee[result])

ARR : [11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]
ITEMS : [10, 20, 30, 40, 5, 0, 11, 78, 90, 65]
Simliar Items : [11  5 30 78]


**np.flip :**
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
- https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [37]:
print('Before Flip :',a)
print('After Flip :',np.flip(a))

Before Flip : [28 34 69 39 29 29 36 28 60 49 43 48 81 86 19]
After Flip : [19 86 81 48 43 49 60 28 36 29 29 39 69 34 28]


In [39]:
print(b)

[[22 26  5 32]
 [71 80 14 30]
 [58 36 97 10]
 [85  4 65 96]
 [54 23 85 16]
 [13  3  9 48]]


In [40]:
print(np.flip(b)) # both filp

[[48  9  3 13]
 [16 85 23 54]
 [96 65  4 85]
 [10 97 36 58]
 [30 14 80 71]
 [32  5 26 22]]


In [41]:
# Flip an array vertically (axis=0).
print(np.flip(b,axis=0))

[[13  3  9 48]
 [54 23 85 16]
 [85  4 65 96]
 [58 36 97 10]
 [71 80 14 30]
 [22 26  5 32]]


In [43]:
# Flip an array horizontally (axis=1).
print(np.flip(b,axis=1))

[[32  5 26 22]
 [30 14 80 71]
 [10 97 36 58]
 [96 65  4 85]
 [16 85 23 54]
 [48  9  3 13]]
