### SESSION 13 - NumPy Fundamentals
### What is numpy?
- NumPy is the fundamental package for scientific computing in Python. 
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays :
- There are 2 ways to importing the numpy module :
    - **`import numpy as np`**
    - **`from numpy import *`**

In [64]:
import numpy as np
# it is vector
a = np.array([1,2,3,4])
print('a :',a)
print('type of a :',type(a))

a : [1 2 3 4]
type of a : <class 'numpy.ndarray'>


### Creating a 2D and 3D numpy arrays:

In [65]:
from numpy import *
# 2D array (it is matrix)
b = array([[1,2,3],[4,5,6]])
print('2D:',b)

2D: [[1 2 3]
 [4 5 6]]


In [66]:
# 3D array (it is tensor)
c = array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(c)

[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


#### Creating a numpy with different `dtype`:

In [67]:
f = array([1,2,3,4] , dtype=float)
c = array([1,2,3,4] , dtype=complex)
tf = array([1,2,0,4] , dtype=bool) # non integer value consider as True
print('float :',f)
print('complex :',c)
print('boolean :',tf)

float : [1. 2. 3. 4.]
complex : [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
boolean : [ True  True False  True]


#### .arange() function :
- The Numpy arange function **generates a NumPy array** with evenly spaced values based on the start and stops intervals specified upon declaration.
- To use the arange function, we will create a new script with the NumPy library imported as np.
- Next, we will declare a new variable number and set this equal to np. arange().
- **Syntax :** `numpy.arange([start],stop,[step],dtype=None)`

In [68]:
from numpy import *
e = arange(5,10)
e1 = arange(5,10,2)
print(e)
print(e1)

[5 6 7 8 9]
[5 7 9]


#### .reshape() function :
- The numpy.reshape() function is used to **change the shape (dimensions) of an array without changing its data.** 
- This function **returns a new array with the same data but with a different shape.**
- The numpy.reshape() function is useful when we need to change the dimensions of an array.
- **for example,** when we want to convert a one-dimensional array into a two-dimensional array or vice versa. 
- It can also be used to create arrays with a specific shape, such as matrices and tensors.
- **Syntax :** `numpy.reshape(a, newshape, order='C')`
    - **a :** This is the source array which we want to reshape.
    - **new_shape:** The shape in which we want to convert our original array should be compatible with the original array.
    - **order:** {'C', 'F', 'A'}, optional  
- **NOTE:** the both product of the array number is equal to number of item that are present in inside the array.

In [69]:
from numpy import *
r = arange(1,13)
re = reshape(r,(2,6))
print(re)
re1 = reshape(r,(6,2))
print(re1)
re3 = reshape(r,(3,4))
print(re3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### numpy.ones() function :
- Python numpy.ones() function returns a new array of given shape and data type, where the element’s value is set to 1.
- **For example,**It is useful in deep learning to intialize the weights values
- **syntax**: `ones(shape, dtype=None, order='C')`

In [70]:
from numpy import *
o = ones((2,4), dtype=int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


#### .zeros() function :
- Python numpy.zeros() function returns a new array of given shape and type, where the element’s value as 0.
- The elements are having the default data type as the float. That’s why the zeros are 0.
- **syntax**: `zeros(shape, dtype=None, order='C')`

In [71]:
from numpy import *
z = zeros((3,3), dtype=int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### numpy.random.random() function :
- The functions which are used for generating random numbers.
- here 1st random is class name and other one is method name follows OOP concept

In [72]:
from numpy import *
# creating default random varible between 0 to 1
r = random.random((3,3))
print(r)

[[0.44509628 0.19277255 0.29745395]
 [0.25306869 0.48937346 0.56124047]
 [0.58278016 0.28991606 0.16215481]]


#### .linspace() function : (Linear/ linearly space)
- NumPy function that returns evenly spaced numbers over a specified interval.
- Use plotting ther ML algorithm result.
- **syntax :** - `linspace(start, stop, num=50, dtype=None, axis=0)` 
    - **start:** The starting value of the sequence.
    - **stop:** The end value of the sequence, unless endpoint is set to False.
    - **num:** The number of evenly spaced numbers to generate. Default is 50.
    - **axis:** The axis along which to generate the evenly spaced numbers. Default is 0.

In [73]:
from numpy import *
ls = linspace(1,10,5)
print(ls)

[ 1.    3.25  5.5   7.75 10.  ]


#### .identity() function :
- Returns a square identity matrix of size n x n.
- means digonally items are 1 and remaing are all 0's
- **syntax:** `numpy.identity(n, dtype=None)`
    - **n:** The size of the identity matrix to be generated.
    - **dtype:** The data type of the output array and default is float.

In [74]:
from numpy import *
i = identity(3, dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Numpy Arrays Attributes of a Numpy Array
- NumPy array (ndarray class) is the most used construct of NumPy in Machine Learning and Deep Learning. Let us look into some important attributes of this NumPy array.

In [75]:
from numpy import *
a1 = arange(10)
a2 = arange(12,dtype=float).reshape(3,4)
a3 = arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


#### .ndim attribute
- In NumPy, **.ndim** is a function that returns the number of dimensions of a given NumPy array..

In [76]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


#### .shape attribute
- In NumPy, the **.shape** attribute of a NumPy array is used to determine the dimensions of the array. 
- It returns a tuple of integers that represent the size of the array in each dimension.

In [77]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


####  .size attribute
- In NumPy, **.size** is an attribute of a NumPy array that returns the total number of elements in the array.

In [78]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


####  .itemsize attribute
- In NumPy, **.itemsize** is an attribute of a NumPy array that returns the size (in bytes) of each element in the array.
- Shows occupation of memory of the each item of inside the array 

In [79]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


#### .dtype attribute
- In NumPy,**.dtype** is an attribute of a NumPy array that returns the data type of the elements in the array.

In [80]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing datatype using .astype() method :
- **.astype()** is a method of a NumPy array that is used to **change the data type of the elements in the array.**
- More useful in converting the Float datatype reduction in integer value 

In [81]:
print('a2 dtype :',a2.dtype)
print(a2)
change_dtype = a2.astype(int32)
print(change_dtype)
print('a2 dtype :',change_dtype.dtype)

a2 dtype : float64
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2 dtype : int32


#### Numpy Array Operations :
- Use for perfroming mathematical operation 

In [82]:
from numpy import *
a1 = arange(12).reshape(3,4)
a2 = arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Scalar Operations:
- A scalar operation is an **operation between a scalar value (a single number) and an array.**
- In NumPy, scalar operations can be performed using arithmetic operators such as +, -, *, and /. 
- When a scalar value is added to an array, the scalar value is added to each element in the array.

In [83]:
from numpy import *
print('Addintion of 2 to each element of array :')
print(a1 + 2)
print('Multiply by 2 to each element of array :')
print(a1 * 2)
print('Division by 2 to each element of array :')
print(a1 / 2)
print('Power of each element of array :')
print(a1 ** 2)

Addintion of 2 to each element of array :
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
Multiply by 2 to each element of array :
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Division by 2 to each element of array :
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
Power of each element of array :
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


#### Relational Operators : 
- In NumPy, relational operations are performed between arrays and return boolean arrays that indicate whether each element in the array satisfies a given condition.

#### Comparison Operations:
- NumPy provides comparison operators such as ==, !=, <, >, <=, and >= for comparing elements in two arrays. 
- These operations return a boolean array with the same shape as the input arrays, where True indicates that the condition is satisfied, and False indicates that it is not.

In [84]:
print(a1 >= 0)
print(a1 == 2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False  True False]
 [False False False False]
 [False False False False]]


#### Vector Operations:
- A vector operation is an **operation between two arrays of the same size.** 
- In NumPy, vector operations can also be performed using arithmetic operators. 
- When two arrays are added, the corresponding elements in each array are added together. 
- Similarly, for subtraction and multiplication, the corresponding elements in each array are subtracted and multiplied.
- **Note :** It's important to note that vector operations can only be performed on arrays of the same shape. If the arrays have different shapes, NumPy will raise a ValueError.

In [85]:
from numpy import *
print(a1)
print(a2)
print('Adds corresponding elements in arrays a1 and a2 :')
print(a1 + a2)
print('Subtracts corresponding elements in arrays a1 and a2 :')
print(a1 - a2)
print('Multiplication corresponding elements in arrays a1 and a2 :')
print(a1 * a2)
print('Division corresponding elements in arrays a1 and a2 :')
print(a1 / a2)
print('Power corresponding elements in arrays a1 and a2 :')
print(a1 ** a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Adds corresponding elements in arrays a1 and a2 :
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Subtracts corresponding elements in arrays a1 and a2 :
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
Multiplication corresponding elements in arrays a1 and a2 :
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
Division corresponding elements in arrays a1 and a2 :
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
Power corresponding elements in arrays a1 and a2 :
[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]


### Numpy Array Function :
**max() / min() / sum() / prod():**

In [86]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[86., 93., 66.],
       [28.,  1., 13.],
       [45., 84., 19.]])

In [87]:
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

93.0
1.0
435.0
13799778632640.0


In [88]:
# find maximum of each columns or rows
# 0 reprents column and 1 represents row
print(np.max(a1,axis=1))

[93. 28. 84.]


**mean() / median() / std() / var():**

In [89]:
print(np.var(a1))
print(np.mean(a1))
print(np.median(a1))

1085.7777777777778
48.333333333333336
45.0


**dot product :**
- The condition to identify whether two vectors can be dot-multiplied is that they must have the same dimensionality.
- In numpy, you can compute the dot product of two arrays using the dot() function. 
- The dot() function takes two array arguments and returns their dot product.

In [90]:
import numpy as np
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)
print(a3)
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [91]:
dp = np.dot(a3,a4)
print(dp)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [92]:
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


**log and exponemts in numpy**
- **np.log() :**
    - To calculate the natural logarithm of an array or a scalar, you can use the **numpy.log** function
- **np.exp() :**
    - To calculate the exponential of an array or a scalar, you can use the **numpy.exp** function

In [93]:
print(np.log(a1))

[[4.4543473  4.53259949 4.18965474]
 [3.33220451 0.         2.56494936]
 [3.80666249 4.4308168  2.94443898]]


In [94]:
print(np.exp(a1))

[[2.23524660e+37 2.45124554e+40 4.60718663e+28]
 [1.44625706e+12 2.71828183e+00 4.42413392e+05]
 [3.49342711e+19 3.02507732e+36 1.78482301e+08]]


**round()/floor()/ceil()**
- **round() :**
    - The round() function rounds the elements of an array to the nearest integer or to a specified number of decimals
- **floor() :**
    - The floor() function rounds the elements of an array down to the nearest integer
- **ceil() :**
    - The ceil() function rounds the elements of an array up to the nearest integer

In [95]:
# round()
arr = np.array([1.23,2.49,4.51])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 2. 5.]


In [96]:
# floor()
arr1 = np.array([1.23,2.49,4.51,4.80])
floor_arr1 = np.floor(arr1)
print(floor_arr1)

[1. 2. 4. 4.]


In [97]:
# ceil()
arr3 = np.array([1.23,2.49,4.11,1.00])
ceil_arr3 = np.ceil(arr3)
print(ceil_arr3)

[2. 3. 5. 1.]


In [98]:
#floor()
print(np.floor(np.random.random((2,3))*100))

[[29. 97. 56.]
 [32. 37. 72.]]


#### 2D/3D Indexing and Slicing in Numpy:

In [99]:
import numpy as np
n1 = np.arange(10)
n2 = np.arange(12).reshape(3,4)
n3 = np.arange(8).reshape(2,2,2)

**Indexing of 2D array:**
- For accessing the element we give the 1st row number and then column numbers.
- **NOTE:**Array start form 0 index

In [100]:
print(n2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [101]:
print(n2[2,2])
print(n2[1,0])
print(n2[2,3])
print(n2[0,2])
print(n2[1,3])

10
4
11
2
7


**Indexing of 3D array:**
- For accessing the element 1st we give index number of the array then we give the row number and then column numbers.
- 3D array is made from 2D array
- **NOTE:**Array start form 0 index

In [102]:
print(n3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [103]:
print(n3[0,1,1])
print(n3[1,1,0])
print(n3[1,0,0])
print(n3[0,0,1])
print(n3[1,0,1])
print(n3[0,0,0])
print(n3[0,1,0])
print(n3[1,1,1])

3
6
4
1
5
0
2
7


#### Slicing :
- Slicing is a useful operation in NumPy that allows you to extract a portion of an array. 
- You can slice a NumPy array by specifying a range of indices to extract.
- syntax for slicing a NumPy array is as follows: **array[start:stop:step]**

In [104]:
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [105]:
print(n1[2:6])
print(n1[1:8:2])

[2 3 4 5]
[1 3 5 7]


**Accessing row and columns for 2d array :**

In [106]:
print(n2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(n2[0,:]) # print row 
print(n2[:,2]) # print 2nd index column
print(n2[2,:]) # print 3rd index row 

[0 1 2 3]
[ 2  6 10]
[ 8  9 10 11]


In [11]:
print(n2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [12]:
print(n2[1,::3])

[4 7]


In [13]:
print(n2[0:2 , 1:])

[[1 2 3]
 [5 6 7]]


**Accessing row and columns for 3d array :**

In [14]:
n3 = np.arange(27).reshape(3,3,3)
print(n3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
print(n3[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [16]:
print(n3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
print(n3[0,1,:])

[3 4 5]


In [18]:
print(n3[1,:,1])

[10 13 16]


In [19]:
print(n3[2,1:,1:])

[[22 23]
 [25 26]]


In [20]:
print(n3[::2, 0 , ::2])

[[ 0  2]
 [18 20]]


### Iterating :

In [21]:
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
# loop
for ele in n1:
    print(ele)

0
1
2
3
4
5
6
7
8
9


In [23]:
print(n2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
# loop on 2D array
for ele in n2:
    print(ele)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [27]:
# loop on 3D array
for ele in n3:
    print(ele)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


**np.nditer() function:** 
- It is a NumPy function that provides an efficient way to iterate over elements of a NumPy array. 
- It allows iterating over multiple arrays simultaneously and also provides a number of optional arguments that can be used to customize the iteration process.

In [29]:
for ele in np.nditer(n3):
    print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping in numpy :
- **np.reshape()**
- **np.transpose()**
- **np.ravel()**

**np.transpose():**
- The transpose operation in numpy is generally applied on 2d arrays to swipe the rows and columns of an array. 
- **For example**, a numpy array of shape (2, 3) becomes a numpy array of shape (3, 2) after the operation wherein the first row becomes the first column and the second row becomes the second column. Also, conversely, the first column becomes the first row, the second column becomes the second row, and the third column becomes the third row post the transpose.
- You can use the numpy ndarary transpose() function to transpose a numpy array. You can also use the .T numpy array attribute to transpose a 2d array.
- syntax: **arr.transpose() or arr.T**

In [44]:
# example of transpose()
print('Original 2D array :')
print(n2)
print('Transpose of 2D Array :')
print(n2.transpose())
print(n2.T)

Original 2D array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose of 2D Array :
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**np.ravel():**
- Converting n dimesion array into 1D array.
- syntax: **arr.ravel()**

In [43]:
print('Original 3D array :')
print(n3)
print('Conveting into 1D array using ravel() :')
print(n3.ravel())

Original 3D array :
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Conveting into 1D array using ravel() :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### Stacking :
- In NumPy, you can stack arrays along different axes using the functions.
    - **np.hstack() : horizontal stacking**
    - **np.vstack() : vertical stacking**
- Some times we have multiple data source means sometimes data come form databases , API and another data comes from web scrapping etc. so that data is similar data for multiple sourse then we can stack the data for data analysis.
- **NOTE :** Shape of the array should ne same

**np.hstack():**
- horizontal stacking means join/append the columns array with another array.
- This function stacks arrays horizontally (along axis 1), which means it **appends the columns of one array to the end of another array**.
- syntax : **np.hstack((arr1, arr2))**

In [61]:
# example :
nn1 = np.arange(12).reshape(3,4)
nn2 = np.arange(12,24).reshape(3,4)

In [62]:
# Ex.
np.hstack((nn1,nn2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

**np.vstack():**
- vertical stacking 
- This function stacks arrays vertically (along axis 0), which means it appends the rows of one array to the end of another array.
- syntax : **np.vstack((arr1, arr2))**

In [63]:
# Ex.
np.vstack((nn1,nn2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])