### SESSION 13 - NumPy Fundamentals
#### What is numpy?
- NumPy is the fundamental package for scientific computing in Python. 
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

#### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### Creating Numpy Arrays :
- There are 2 ways to importing the numpy module :
    - **`import numpy as np`**
    - **`from numpy import *`**

In [4]:
import numpy as np
# it is vector
a = np.array([1,2,3,4])
print('a :',a)
print('type of a :',type(a))

a : [1 2 3 4]
type of a : <class 'numpy.ndarray'>


#### Creating a 2D and 3D numpy arrays:

In [8]:
from numpy import *
# 2D array (it is matrix)
b = array([[1,2,3],[4,5,6]])
print('2D:',b)

2D: [[1 2 3]
 [4 5 6]]


In [11]:
# 3D array (it is tensor)
c = array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(c)

[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


#### Creating a numpy with different `dtype`:

In [14]:
f = array([1,2,3,4] , dtype=float)
c = array([1,2,3,4] , dtype=complex)
tf = array([1,2,0,4] , dtype=bool) # non integer value consider as True
print('float :',f)
print('complex :',c)
print('boolean :',tf)

float : [1. 2. 3. 4.]
complex : [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
boolean : [ True  True False  True]


#### .arange() function :
- The Numpy arange function **generates a NumPy array** with evenly spaced values based on the start and stops intervals specified upon declaration.
- To use the arange function, we will create a new script with the NumPy library imported as np.
- Next, we will declare a new variable number and set this equal to np. arange().
- **Syntax :** `numpy.arange([start],stop,[step],dtype=None)`

In [23]:
from numpy import *
e = arange(5,10)
e1 = arange(5,10,2)
print(e)
print(e1)

[5 6 7 8 9]
[5 7 9]


#### .reshape() function :
- The numpy.reshape() function is used to **change the shape (dimensions) of an array without changing its data.** 
- This function **returns a new array with the same data but with a different shape.**
- The numpy.reshape() function is useful when we need to change the dimensions of an array.
- **for example,** when we want to convert a one-dimensional array into a two-dimensional array or vice versa. 
- It can also be used to create arrays with a specific shape, such as matrices and tensors.
- **Syntax :** `numpy.reshape(a, newshape, order='C')`
    - **a :** This is the source array which we want to reshape.
    - **new_shape:** The shape in which we want to convert our original array should be compatible with the original array.
    - **order:** {'C', 'F', 'A'}, optional  
- **NOTE:** the both product of the array number is equal to number of item that are present in inside the array.

In [7]:
from numpy import *
r = arange(1,13)
re = reshape(r,(2,6))
print(re)
re1 = reshape(r,(6,2))
print(re1)
re3 = reshape(r,(3,4))
print(re3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### numpy.ones() function :
- Python numpy.ones() function returns a new array of given shape and data type, where the element’s value is set to 1.
- **For example,**It is useful in deep learning to intialize the weights values
- **syntax**: `ones(shape, dtype=None, order='C')`

In [8]:
from numpy import *
o = ones((2,4), dtype=int)
print(o)

[[1 1 1 1]
 [1 1 1 1]]


#### .zeros() function :
- Python numpy.zeros() function returns a new array of given shape and type, where the element’s value as 0.
- The elements are having the default data type as the float. That’s why the zeros are 0.
- **syntax**: `zeros(shape, dtype=None, order='C')`

In [9]:
from numpy import *
z = zeros((3,3), dtype=int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### numpy.random.random() function :
- The functions which are used for generating random numbers.
- here 1st random is class name and other one is method name follows OOP concept

In [21]:
from numpy import *
# creating default random varible between 0 to 1
r = random.random((3,3))
print(r)

[[0.73965092 0.1750063  0.19822543]
 [0.8223754  0.01410322 0.01425468]
 [0.11114968 0.69797665 0.48849288]]


#### .linspace() function : (Linear/ linearly space)
- NumPy function that returns evenly spaced numbers over a specified interval.
- Use plotting ther ML algorithm result.
- **syntax :** - `linspace(start, stop, num=50, dtype=None, axis=0)` 
    - **start:** The starting value of the sequence.
    - **stop:** The end value of the sequence, unless endpoint is set to False.
    - **num:** The number of evenly spaced numbers to generate. Default is 50.
    - **axis:** The axis along which to generate the evenly spaced numbers. Default is 0.

In [40]:
from numpy import *
ls = linspace(1,10,5)
print(ls)

[ 1.    3.25  5.5   7.75 10.  ]


#### .identity() function :
- Returns a square identity matrix of size n x n.
- means digonally items are 1 and remaing are all 0's
- **syntax:** `numpy.identity(n, dtype=None)`
    - **n:** The size of the identity matrix to be generated.
    - **dtype:** The data type of the output array and default is float.

In [1]:
from numpy import *
i = identity(3, dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Numpy Arrays Attributes of a Numpy Array
- NumPy array (ndarray class) is the most used construct of NumPy in Machine Learning and Deep Learning. Let us look into some important attributes of this NumPy array.

In [4]:
from numpy import *
a1 = arange(10)
a2 = arange(12,dtype=float).reshape(3,4)
a3 = arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


#### .ndim attribute
- In NumPy, **.ndim** is a function that returns the number of dimensions of a given NumPy array..

In [5]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


#### .shape attribute
- In NumPy, the **.shape** attribute of a NumPy array is used to determine the dimensions of the array. 
- It returns a tuple of integers that represent the size of the array in each dimension.

In [6]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


####  .size attribute
- In NumPy, **.size** is an attribute of a NumPy array that returns the total number of elements in the array.

In [7]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


####  .itemsize attribute
- In NumPy, **.itemsize** is an attribute of a NumPy array that returns the size (in bytes) of each element in the array.
- Shows occupation of memory of the each item of inside the array 

In [8]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


#### .dtype attribute
- In NumPy,**.dtype** is an attribute of a NumPy array that returns the data type of the elements in the array.

In [9]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


#### Changing datatype using .astype() method :
- **.astype()** is a method of a NumPy array that is used to **change the data type of the elements in the array.**
- More useful in converting the Float datatype reduction in integer value 

In [43]:
print('a2 dtype :',a2.dtype)
print(a2)
change_dtype = a2.astype(int32)
print(change_dtype)
print('a2 dtype :',change_dtype.dtype)

a2 dtype : float64
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2 dtype : int32


#### Numpy Array Operations :
- Use for perfroming mathematical operation 

In [3]:
from numpy import *
a1 = arange(12).reshape(3,4)
a2 = arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Scalar Operations:
- A scalar operation is an **operation between a scalar value (a single number) and an array.**
- In NumPy, scalar operations can be performed using arithmetic operators such as +, -, *, and /. 
- When a scalar value is added to an array, the scalar value is added to each element in the array.

In [18]:
from numpy import *
print('Addintion of 2 to each element of array :')
print(a1 + 2)
print('Multiply by 2 to each element of array :')
print(a1 * 2)
print('Division by 2 to each element of array :')
print(a1 / 2)
print('Power of each element of array :')
print(a1 ** 2)

Addintion of 2 to each element of array :
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
Multiply by 2 to each element of array :
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
Division by 2 to each element of array :
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
Power of each element of array :
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


#### Relational Operators : 
- In NumPy, relational operations are performed between arrays and return boolean arrays that indicate whether each element in the array satisfies a given condition.

#### Comparison Operations:
- NumPy provides comparison operators such as ==, !=, <, >, <=, and >= for comparing elements in two arrays. 
- These operations return a boolean array with the same shape as the input arrays, where True indicates that the condition is satisfied, and False indicates that it is not.

In [19]:
print(a1 >= 0)
print(a1 == 2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False  True False]
 [False False False False]
 [False False False False]]


#### Vector Operations:
- A vector operation is an **operation between two arrays of the same size.** 
- In NumPy, vector operations can also be performed using arithmetic operators. 
- When two arrays are added, the corresponding elements in each array are added together. 
- Similarly, for subtraction and multiplication, the corresponding elements in each array are subtracted and multiplied.
- **Note :** It's important to note that vector operations can only be performed on arrays of the same shape. If the arrays have different shapes, NumPy will raise a ValueError.

In [26]:
from numpy import *
print(a1)
print(a2)
print('Adds corresponding elements in arrays a1 and a2 :')
print(a1 + a2)
print('Subtracts corresponding elements in arrays a1 and a2 :')
print(a1 - a2)
print('Multiplication corresponding elements in arrays a1 and a2 :')
print(a1 * a2)
print('Division corresponding elements in arrays a1 and a2 :')
print(a1 / a2)
print('Power corresponding elements in arrays a1 and a2 :')
print(a1 ** a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Adds corresponding elements in arrays a1 and a2 :
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Subtracts corresponding elements in arrays a1 and a2 :
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
Multiplication corresponding elements in arrays a1 and a2 :
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
Division corresponding elements in arrays a1 and a2 :
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
Power corresponding elements in arrays a1 and a2 :
[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]


#### Numpy Array Function :
**max() / min() / sum() / prod():**

In [3]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[71., 86., 43.],
       [92., 45., 60.],
       [34., 61., 37.]])

In [4]:
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

92.0
34.0
529.0
5004806869713600.0


In [5]:
# find maximum of each columns or rows
# 0 reprents column and 1 represents row
print(np.max(a1,axis=1))

[86. 92. 61.]


**mean() / median() / std() / var():**

In [17]:
print(np.var(a1))
print(np.mean(a1))
print(np.median(a1))

391.95061728395063
58.77777777777778
60.0


**dot product :**
- The condition to identify whether two vectors can be dot-multiplied is that they must have the same dimensionality.
- In numpy, you can compute the dot product of two arrays using the dot() function. 
- The dot() function takes two array arguments and returns their dot product.

In [18]:
import numpy as np
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)
print(a3)
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [19]:
dp = np.dot(a3,a4)
print(dp)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [20]:
print(a4)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
**log and exponemts**