### SESSION 13 - NumPy Fundamentals
#### What is numpy?
- NumPy is the fundamental package for scientific computing in Python. 
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

#### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#### Creating Numpy Arrays :
- There are 2 ways to importing the numpy module :
    - **`import numpy as np`**
    - **`from numpy import *`**

In [4]:
import numpy as np
# it is vector
a = np.array([1,2,3,4])
print('a :',a)
print('type of a :',type(a))

a : [1 2 3 4]
type of a : <class 'numpy.ndarray'>


#### Creating a 2D and 3D numpy arrays:

In [8]:
from numpy import *
# 2D array (it is matrix)
b = array([[1,2,3],[4,5,6]])
print('2D:',b)

2D: [[1 2 3]
 [4 5 6]]


In [11]:
# 3D array (it is tensor)
c = array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(c)

[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


#### Creating a numpy with different `dtype`:

In [14]:
f = array([1,2,3,4] , dtype=float)
c = array([1,2,3,4] , dtype=complex)
tf = array([1,2,0,4] , dtype=bool) # non integer value consider as True
print('float :',f)
print('complex :',c)
print('boolean :',tf)

float : [1. 2. 3. 4.]
complex : [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
boolean : [ True  True False  True]


#### Numpy.arange() function :
- The Numpy arange function **generates a NumPy array** with evenly spaced values based on the start and stops intervals specified upon declaration.
- To use the arange function, we will create a new script with the NumPy library imported as np.
- Next, we will declare a new variable number and set this equal to np. arange().
- **Syntax :** `numpy.arange([start],stop,[step],dtype=None)`

In [23]:
from numpy import *
e = arange(5,10)
e1 = arange(5,10,2)
print(e)
print(e1)

[5 6 7 8 9]
[5 7 9]


#### Numpy.reshape() function :
- The numpy.reshape() function is used to **change the shape (dimensions) of an array without changing its data.** 
- This function **returns a new array with the same data but with a different shape.**
- The numpy.reshape() function is useful when we need to change the dimensions of an array.
- **for example,** when we want to convert a one-dimensional array into a two-dimensional array or vice versa. 
- It can also be used to create arrays with a specific shape, such as matrices and tensors.
- **Syntax :** `numpy.reshape(a, newshape, order='C')`
    - **a :** This is the source array which we want to reshape.
    - **new_shape:** The shape in which we want to convert our original array should be compatible with the original array.
    - **order:** {'C', 'F', 'A'}, optional

In [29]:
from numpy import *
r = arange(1,13)
re = reshape(r,(2,6))
print(re)
re1 = reshape(r,(6,2))
print(re1)
re3 = reshape(r,(3,4))
print(re3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### numpy.ones() function :
- Python numpy.ones() function returns a new array of given shape and data type, where the element’s value is set to 1.
- **For example,**It is useful in deep learning to intialize the weights values
- **syntax**: `ones(shape, dtype=None, order='C')`

In [9]:
from numpy import *
o = ones((2,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### numpy.zeros() function :
- Python numpy.zeros() function returns a new array of given shape and type, where the element’s value as 0.
- The elements are having the default data type as the float. That’s why the zeros are 0.
- **syntax**: `zeros(shape, dtype=None, order='C')`

In [10]:
from numpy import *
z = zeros((2,10), dtype=int)
print(z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
