### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([21, 62, 27,  6, 84, 35, 69, 71, 57, 59, 57, 38, 91, 51, 46])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[16, 79, 19, 90],
       [61, 29, 39, 42],
       [44, 99, 94, 64],
       [22, 43, 35, 66],
       [35, 41, 15,  4],
       [58, 31, 84, 37]])

In [4]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [ 6 21 27 35 38 46 51 57 57 59 62 69 71 84 91]
Sorted order : [91 84 71 69 62 59 57 57 51 46 38 35 27 21  6]


In [5]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[16 79 19 90]
 [61 29 39 42]
 [44 99 94 64]
 [22 43 35 66]
 [35 41 15  4]
 [58 31 84 37]]

column-wise sort :
[[16 29 15  4]
 [22 31 19 37]
 [35 41 35 42]
 [44 43 39 64]
 [58 79 84 66]
 [61 99 94 90]]

row-wise sort :
[[16 19 79 90]
 [29 39 42 61]
 [44 64 94 99]
 [22 35 43 66]
 [ 4 15 35 41]
 [31 37 58 84]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[ 21  62  27   6  84  35  69  71  57  59  57  38  91  51  46 200]
[[16. 79. 19. 90.  1.]
 [61. 29. 39. 42.  1.]
 [44. 99. 94. 64.  1.]
 [22. 43. 35. 66.  1.]
 [35. 41. 15.  4.  1.]
 [58. 31. 84. 37.  1.]]


**np.concatenate:**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


**np.unique :**
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
- Ex.Imagine 1 student register for multiple courses , but we want those user they purches the course so it useful to identify the unique users from course 
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [10]:
# Ex
e = np.array([1,2,3,3,4,4,5,5,6,6])
print("E :",e)
print('Unique Values :',np.unique(e))

E : [1 2 3 3 4 4 5 5 6 6]
Unique Values : [1 2 3 4 5 6]


**np.expand_dims :**
- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.
- means 1D to 2D convertion or 3d to 4D conversion.
- https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [11]:
print('E:',e)
print('2D :',np.expand_dims(e,axis=0)) # axis 0 is row
print(np.expand_dims(e,axis=0).shape)

E: [1 2 3 3 4 4 5 5 6 6]
2D : [[1 2 3 3 4 4 5 5 6 6]]
(1, 10)


In [12]:
print(np.expand_dims(e,axis=1)) # axis 1 is col
print(np.expand_dims(e,axis=1).shape)

[[1]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]]
(10, 1)


**np.where :**
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [13]:
print(e)
# Ex.find all indices with value greater than 4
print(np.where(e>4))

[1 2 3 3 4 4 5 5 6 6]
(array([6, 7, 8, 9], dtype=int64),)


In [14]:
# Ex.replace all values < 4 with 0
print(np.where(e<4, 0, e))

[0 0 0 0 4 4 5 5 6 6]


**np.argmax :**
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [15]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [16]:
print(np.argmax(e))

8


In [17]:
# 2D 
print(b)

[[16 79 19 90]
 [61 29 39 42]
 [44 99 94 64]
 [22 43 35 66]
 [35 41 15  4]
 [58 31 84 37]]


In [18]:
print(np.argmax(b, axis=0)) # col = 0

[1 2 2 0]


In [19]:
print(np.argmax(b, axis=1)) # row = 1

[3 0 1 3 1 2]


**np.argmin :**
- give the min number index

In [20]:
print(e)
print(np.argmin(e))

[1 2 3 3 4 4 5 5 6 6]
0


In [21]:
print(np.argmin(b, axis=0))

[0 1 4 4]


In [22]:
print(np.argmin(b, axis=1))

[0 1 0 0 3 1]


**np.cumsum :**
- numpy.cumsum() function is used when we want to compute the **cumulative sum of array elements over a given axis.**
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [23]:
# Ex.1D
print(a)
print('cumilative sum : ',np.cumsum(a))

[21 62 27  6 84 35 69 71 57 59 57 38 91 51 46]
cumilative sum :  [ 21  83 110 116 200 235 304 375 432 491 548 586 677 728 774]


In [24]:
# Ex.2D
print(b)

[[16 79 19 90]
 [61 29 39 42]
 [44 99 94 64]
 [22 43 35 66]
 [35 41 15  4]
 [58 31 84 37]]


In [25]:
print(np.cumsum(b))

[  16   95  114  204  265  294  333  375  419  518  612  676  698  741
  776  842  877  918  933  937  995 1026 1110 1147]


In [26]:
print(np.cumsum(b,axis=0)) # 1 = row

[[ 16  79  19  90]
 [ 77 108  58 132]
 [121 207 152 196]
 [143 250 187 262]
 [178 291 202 266]
 [236 322 286 303]]


In [27]:
print(np.cumsum(b,axis=1)) # 0 = col

[[ 16  95 114 204]
 [ 61  90 129 171]
 [ 44 143 237 301]
 [ 22  65 100 166]
 [ 35  76  91  95]
 [ 58  89 173 210]]


**np.cumprod :**
- numpy.cumprod() function is used multiplication

In [28]:
print(e)
print(np.cumprod(e))

[1 2 3 3 4 4 5 5 6 6]
[     1      2      6     18     72    288   1440   7200  43200 259200]


In [29]:
print(np.cumprod(b))

[         16        1264       24016     2161440   131847840  -471379936
 -1203948320   973778112  -103436032 -1650232576  -503039488 -2129756160
   390004736  -409665536 -1453391872 -1434583040  1329201152 -1337327616
  1414922240  1364721664  1844445184  1343225856  1161822208    37748736]


**np.percentile :**
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
- **formula :** p = (n/N)*100
    - p : percentile
    - n : Number of values fall under(below) 'x' 
    - N : Total count of population

In [30]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [31]:
print(np.percentile(e,0))
print(np.percentile(e,50))
print(np.percentile(e,100))

1.0
4.0
6.0


**np.histogram:**
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution for the graphical form.
- https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [32]:
#Ex.
ee = np.array([11,53,28,50,38,37,94,92,5,30,68,9,78,2,21])
print(ee)

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]


In [33]:
print(np.histogram(ee,bins=[0,10,20,30,40,50,60,70,80,90,100]))

(array([3, 1, 2, 3, 0, 2, 1, 1, 0, 2], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


**np.corrcoef :**
- Return Pearson product-moment correlation coefficients.
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [34]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


**np.isin :**
- With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.
- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [35]:
print("ARR :",ee)
i = [10,20,30,40,5,0,11,78,90,65]
print('ITEMS :',i)
result = np.isin(ee,i)
print('Simliar Items :',ee[result])

ARR : [11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]
ITEMS : [10, 20, 30, 40, 5, 0, 11, 78, 90, 65]
Simliar Items : [11  5 30 78]


**np.flip :**
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
- https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [36]:
print('Before Flip :',a)
print('After Flip :',np.flip(a))

Before Flip : [21 62 27  6 84 35 69 71 57 59 57 38 91 51 46]
After Flip : [46 51 91 38 57 59 57 71 69 35 84  6 27 62 21]


In [37]:
print(b)

[[16 79 19 90]
 [61 29 39 42]
 [44 99 94 64]
 [22 43 35 66]
 [35 41 15  4]
 [58 31 84 37]]


In [38]:
print(np.flip(b)) # both filp

[[37 84 31 58]
 [ 4 15 41 35]
 [66 35 43 22]
 [64 94 99 44]
 [42 39 29 61]
 [90 19 79 16]]


In [39]:
# Flip an array vertically (axis=0).
print(np.flip(b,axis=0))

[[58 31 84 37]
 [35 41 15  4]
 [22 43 35 66]
 [44 99 94 64]
 [61 29 39 42]
 [16 79 19 90]]


In [40]:
# Flip an array horizontally (axis=1).
print(np.flip(b,axis=1))

[[90 19 79 16]
 [42 39 29 61]
 [64 94 99 44]
 [66 35 43 22]
 [ 4 15 41 35]
 [37 84 31 58]]


**np.put :**
- The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.
- https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [41]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [42]:
np.put(e,[0,4],[90,80])

**np.delete :**
- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.
- https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [47]:
print(e)

print(np.delete(e,0))
print(np.delete(e,[4,5,6]))

[90  2  3  3 80  4  5  5  6  6]
[ 2  3  3 80  4  5  5  6  6]
[90  2  3  3  5  6  6]
