### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [67]:
# Sort this matrix. np.sort()
import numpy as np
arr = np.random.randint(0, 100, (4, 3))
print("Original matrix:")
print(arr)
print('1.sort array :')
print(np.sort(arr))

Original matrix:
[[99 51 92]
 [71 69 58]
 [56 77 30]
 [33 81 59]]
1.sort array :
[[51 92 99]
 [58 69 71]
 [30 56 77]
 [33 59 81]]


In [68]:
# Sort this matrix based on values in 2nd column.
arr = np.random.randint(0, 100, (4, 3))
print("Original matrix:")
print(arr)
print('Sort this matrix based on values in 2nd column.')
print(arr[arr[:, 1].argsort()])

Original matrix:
[[96  6 22]
 [77 65 51]
 [92 75 24]
 [15 12 75]]
Sort this matrix based on values in 2nd column.
[[96  6 22]
 [15 12 75]
 [77 65 51]
 [92 75 24]]


In [69]:
# Sort this matrix based on max value in each row.
print(arr[np.argsort(np.max(arr, axis=1))])

[[15 12 75]
 [77 65 51]
 [92 75 24]
 [96  6 22]]


In [70]:
arr = np.random.randint(0, 100, (4, 3))
print("Original matrix:")
print(arr)
print("sorted based on max value in each row:")
print(arr[np.argsort(np.max(arr, axis=1))])

Original matrix:
[[54 60 84]
 [24 17 81]
 [63 98 75]
 [34 69 82]]
sorted based on max value in each row:
[[24 17 81]
 [34 69 82]
 [54 60 84]
 [63 98 75]]


In [71]:
# Sort based on elements value.
arr = np.random.randint(0, 100, (4, 3))
print("Original matrix:")
print(arr)
print("Sort based on elements value.")
print(np.sort(arr,axis=None).flatten().reshape(4,3))

Original matrix:
[[47 36  4]
 [85 97 83]
 [59 24 62]
 [50 64 26]]
Sort based on elements value.
[[ 4 24 26]
 [36 47 50]
 [59 62 64]
 [83 85 97]]


### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [19]:
import numpy as np
print('marks :')
marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])
print(marks)

# To match the dimensions we use reshape
print('extra subject :')
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
print(extra_subject)

#Two extra students record-
rec1 = np.array([77, 83, 98, 95]).reshape(1, -1)
print(rec1)
rec2 = np.array([92, 71, 52, 61]).reshape(1, -1)
print(rec2)

marks :
[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]
extra subject :
[[41]
 [87]
 [72]
 [36]
 [92]]
[[77 83 98 95]]
[[92 71 52 61]]


In [22]:
# Add marks every student of an extra subject in the same array.
print(np.concatenate([marks, extra_subject], axis=1))

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]


In [24]:
# 2
marks = np.concatenate([marks, rec1, rec2], axis = 0)
print(marks)

[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]
 [77 83 98 95]
 [92 71 52 61]]


In [30]:
# 3. Add extra column with sum of all subjects(5-subjects) marks
sum_of_row = np.sum(marks, axis=1, keepdims=True)
marks = np.concatenate([marks, sum_of_row], axis = 1)
print(marks)

[[ 13  10   9  33  65]
 [ 63  46  90  42 241]
 [ 39  76  13  29 157]
 [ 82   9  29  78 198]
 [ 67  61  59  36 223]
 [ 77  83  98  95 353]
 [ 92  71  52  61 276]]


In [34]:
# Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
sort_array = np.array(sorted(marks, key= lambda x:x[-1], reverse=True))
print(sort_array[:2])

[[ 77  83  98  95 353]
 [ 92  71  52  61 276]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [38]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

# row wise
print('row wise')
print(np.unique(arr, axis=0))

# col wise
print('\ncol wise')
print(np.unique(arr, axis=1))

row wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

col wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [47]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('arr:')
print(arr)
print('\ncol wise filp :')
print(np.flip(arr, axis=0))
print('\nrow wise filp :')
print(np.flip(arr, axis=1))
print('\nboth filp :')
print(np.flip(arr)) # or print(np.flip(arr, axis=[0,1]))

arr:
[[1 2 3]
 [4 5 6]]

col wise filp :
[[4 5 6]
 [1 2 3]]

row wise filp :
[[3 2 1]
 [6 5 4]]

both filp :
[[6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [52]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
X = 6
mask = arr>X
print(np.where(np.any(mask, axis=1))[0])

[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [55]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [60]:
print(np.concatenate([arr1,arr2,arr3]))

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [85]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)

max_ele = arr.argmax() # return  index of max element
min_ele = arr.argmin() # return index of min element
print('Before :',arr.max(), arr.min())

arr = np.delete(arr, max_ele, axis=1)
arr = np.delete(arr, min_ele, axis=1)
print('After :',arr.max(), arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
Before : 998 103
After : 997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 200]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [102]:
#arr = np.random.randint(0, 1000, 100)
arr = np.array([45,200,76,165,150,23,100,104,143,303,207])
print(arr)
arr = np.sort(np.clip(arr, a_min=100, a_max=200))
print(np.cumsum(arr))

[ 45 200  76 165 150  23 100 104 143 303 207]
[ 100  200  300  400  504  647  797  962 1162 1362 1562]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [117]:
arr = np.random.random(100)
print(np.around(arr, decimals=3))

print('0th percentile is equal to minimum value of the array? :')
print(np.percentile(arr, 0) == arr.min())

print('100th percentile is equal to maximum value of the array? :')
print(np.percentile(arr, 100) == arr.max())

print('difference betwen 51th percenile and 50th percentile values :')
print(np.percentile(arr, 51) == np.percentile(arr, 50))

[0.383 0.435 0.888 0.147 0.136 0.914 0.867 0.839 0.299 0.366 0.284 0.937
 0.439 0.822 0.902 0.676 0.102 0.901 0.122 0.56  0.194 0.994 0.985 0.474
 0.268 0.294 0.883 0.24  0.996 0.995 0.618 0.256 0.775 0.965 0.77  0.416
 0.52  0.669 0.509 0.749 0.154 0.39  0.783 0.644 0.294 0.075 0.737 0.665
 0.172 0.989 0.151 0.223 0.83  0.112 0.045 0.295 0.269 0.294 0.507 0.332
 0.672 0.817 0.228 0.892 0.671 0.731 0.436 0.272 0.701 0.052 0.939 0.507
 0.812 0.137 0.906 0.415 0.556 0.758 0.427 0.949 0.539 0.826 0.924 0.487
 0.36  0.632 0.401 0.627 0.455 0.782 0.147 0.022 0.439 0.411 0.378 0.634
 0.889 0.048 0.465 0.973]
0th percentile is equal to minimum value of the array? :
True
100th percentile is equal to maximum value of the array? :
True
difference betwen 51th percenile and 50th percentile values :
False


In [124]:
arr = np.array([7,10, 2, 4, 13, 16])
print(np.percentile(arr, 50))

8.5


In [125]:
arr = np.array( [[1,2,3,4,5], [6,7,8,9,10]] )
print(arr[1, 2])

8
