### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 9, 77, 94, 88, 47, 91, 45, 40, 78, 88, 26, 15, 83, 81, 12])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[79, 14, 90, 72],
       [73, 13, 51, 28],
       [84,  8, 94, 78],
       [51, 57, 33,  8],
       [92, 83, 18, 52],
       [ 2, 80, 57, 15]])

In [4]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [ 9 12 15 26 40 45 47 77 78 81 83 88 88 91 94]
Sorted order : [94 91 88 88 83 81 78 77 47 45 40 26 15 12  9]


In [5]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[79 14 90 72]
 [73 13 51 28]
 [84  8 94 78]
 [51 57 33  8]
 [92 83 18 52]
 [ 2 80 57 15]]

column-wise sort :
[[ 2  8 18  8]
 [51 13 33 15]
 [73 14 51 28]
 [79 57 57 52]
 [84 80 90 72]
 [92 83 94 78]]

row-wise sort :
[[14 72 79 90]
 [13 28 51 73]
 [ 8 78 84 94]
 [ 8 33 51 57]
 [18 52 83 92]
 [ 2 15 57 80]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[  9  77  94  88  47  91  45  40  78  88  26  15  83  81  12 200]
[[79. 14. 90. 72.  1.]
 [73. 13. 51. 28.  1.]
 [84.  8. 94. 78.  1.]
 [51. 57. 33.  8.  1.]
 [92. 83. 18. 52.  1.]
 [ 2. 80. 57. 15.  1.]]


**np.concatenate:**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


**np.unique :**
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
- Ex.Imagine 1 student register for multiple courses , but we want those user they purches the course so it useful to identify the unique users from course 
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
# Ex
e = np.array([1,2,3,3,4,4,5,5,6,6])
print("E :",e)
print('Unique Values :',np.unique(e))

E : [1 2 3 3 4 4 5 5 6 6]
Unique Values : [1 2 3 4 5 6]


**np.expand_dims :**
- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.
- means 1D to 2D convertion or 3d to 4D conversion.
- https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [30]:
print('E:',e)
print('2D :',np.expand_dims(e,axis=0)) # axis 0 is row
print(np.expand_dims(e,axis=0).shape)

E: [1 2 3 3 4 4 5 5 6 6]
2D : [[1 2 3 3 4 4 5 5 6 6]]
(1, 10)


In [29]:
print(np.expand_dims(e,axis=1)) # axis 1 is col
print(np.expand_dims(e,axis=1).shape)

[[1]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]]
(10, 1)


**np.where :**
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [43]:
print(e)
# Ex.find all indices with value greater than 4
print(np.where(e>4))

[1 2 3 3 4 4 5 5 6 6]
(array([6, 7, 8, 9], dtype=int64),)


In [45]:
# Ex.replace all values < 4 with 0
print(np.where(e<4, 0, e))

[0 0 0 0 4 4 5 5 6 6]


**np.argmax :**
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [46]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [54]:
print(np.argmax(e))

8


In [48]:
# 2D 
print(b)

[[79 14 90 72]
 [73 13 51 28]
 [84  8 94 78]
 [51 57 33  8]
 [92 83 18 52]
 [ 2 80 57 15]]


In [75]:
print(np.argmax(b, axis=0)) # col = 0

[4 4 2 2]


In [61]:
print(np.argmax(b, axis=1)) # row = 1

[2 0 2 1 0 1]


**np.argmin :**
- give the min number index

In [62]:
print(e)
print(np.argmin(e))

[1 2 3 3 4 4 5 5 6 6]
0


In [63]:
print(np.argmin(b, axis=0))

[5 2 4 3]


In [59]:
print(np.argmin(b, axis=1))

[1 1 1 3 2 0]


**np.cumsum :**
- numpy.cumsum() function is used when we want to compute the **cumulative sum of array elements over a given axis.**
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [67]:
# Ex.1D
print(a)
print('cumilative sum : ',np.cumsum(a))

[ 9 77 94 88 47 91 45 40 78 88 26 15 83 81 12]
cumilative sum :  [  9  86 180 268 315 406 451 491 569 657 683 698 781 862 874]


In [68]:
# Ex.2D
print(b)

[[79 14 90 72]
 [73 13 51 28]
 [84  8 94 78]
 [51 57 33  8]
 [92 83 18 52]
 [ 2 80 57 15]]


In [72]:
print(np.cumsum(b))

[  79   93  183  255  328  341  392  420  504  512  606  684  735  792
  825  833  925 1008 1026 1078 1080 1160 1217 1232]


In [73]:
print(np.cumsum(b,axis=0)) # 1 = row

[[ 79  14  90  72]
 [152  27 141 100]
 [236  35 235 178]
 [287  92 268 186]
 [379 175 286 238]
 [381 255 343 253]]


In [74]:
print(np.cumsum(b,axis=1)) # 0 = col

[[ 79  93 183 255]
 [ 73  86 137 165]
 [ 84  92 186 264]
 [ 51 108 141 149]
 [ 92 175 193 245]
 [  2  82 139 154]]
