### SESSION 15 - NumPy Tricks

**np.sort :**
- Return a sorted copy of an array.
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([32, 40, 41, 39, 17, 16, 63, 58, 14, 13,  8, 32,  3,  5, 14])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[30, 90, 61, 32],
       [96, 78, 26, 73],
       [73, 28,  4, 60],
       [61, 98, 12, 70],
       [81, 38, 26, 46],
       [98,  6, 23, 29]])

In [4]:
# ascending order
a_s = np.sort(a)
print("Sorted order :",a_s)

# Desending order
d_s = np.sort(a)[::-1]
print("Sorted order :",d_s) 

Sorted order : [ 3  5  8 13 14 14 16 17 32 32 39 40 41 58 63]
Sorted order : [63 58 41 40 39 32 32 17 16 14 14 13  8  5  3]


In [5]:
# col axis = 0 , row axis = 1
c = np.sort(b, axis=0) # column-wise sort in ascending order
r = np.sort(b, axis=1) # row-wise sort in ascending order
print('Original Array :')
print(b)
print()
print('column-wise sort :')
print(c)
print()
print('row-wise sort :')
print(r)

Original Array :
[[30 90 61 32]
 [96 78 26 73]
 [73 28  4 60]
 [61 98 12 70]
 [81 38 26 46]
 [98  6 23 29]]

column-wise sort :
[[30  6  4 29]
 [61 28 12 32]
 [73 38 23 46]
 [81 78 26 60]
 [96 90 26 70]
 [98 98 61 73]]

row-wise sort :
[[30 32 61 90]
 [26 73 78 96]
 [ 4 28 60 73]
 [12 61 70 98]
 [26 38 46 81]
 [ 6 23 29 98]]


**np.append :**
- The numpy.append() appends values along the mentioned axis at the end of the array
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# Append elements in existing 1D & 2D array
aa = np.append(a,200)
print(aa)

# append column
a_a = np.append(b,np.ones((b.shape[0],1)),axis=1)
print(a_a)

[ 32  40  41  39  17  16  63  58  14  13   8  32   3   5  14 200]
[[30. 90. 61. 32.  1.]
 [96. 78. 26. 73.  1.]
 [73. 28.  4. 60.  1.]
 [61. 98. 12. 70.  1.]
 [81. 38. 26. 46.  1.]
 [98.  6. 23. 29.  1.]]


**np.concatenate:**
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [7]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [8]:
# default concatenate row wise
cc = np.concatenate((c,d),axis=0)
print(cc)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# concatenate column wise
cc = np.concatenate((c,d),axis=1)
print(cc)

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


**np.unique :**
- With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
- Ex.Imagine 1 student register for multiple courses , but we want those user they purches the course so it useful to identify the unique users from course 
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [10]:
# Ex
e = np.array([1,2,3,3,4,4,5,5,6,6])
print("E :",e)
print('Unique Values :',np.unique(e))

E : [1 2 3 3 4 4 5 5 6 6]
Unique Values : [1 2 3 4 5 6]


**np.expand_dims :**
- With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array.
- means 1D to 2D convertion or 3d to 4D conversion.
- https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [11]:
print('E:',e)
print('2D :',np.expand_dims(e,axis=0)) # axis 0 is row
print(np.expand_dims(e,axis=0).shape)

E: [1 2 3 3 4 4 5 5 6 6]
2D : [[1 2 3 3 4 4 5 5 6 6]]
(1, 10)


In [12]:
print(np.expand_dims(e,axis=1)) # axis 1 is col
print(np.expand_dims(e,axis=1).shape)

[[1]
 [2]
 [3]
 [3]
 [4]
 [4]
 [5]
 [5]
 [6]
 [6]]
(10, 1)


**np.where :**
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [13]:
print(e)
# Ex.find all indices with value greater than 4
print(np.where(e>4))

[1 2 3 3 4 4 5 5 6 6]
(array([6, 7, 8, 9], dtype=int64),)


In [14]:
# Ex.replace all values < 4 with 0
print(np.where(e<4, 0, e))

[0 0 0 0 4 4 5 5 6 6]


**np.argmax :**
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [15]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [16]:
print(np.argmax(e))

8


In [17]:
# 2D 
print(b)

[[30 90 61 32]
 [96 78 26 73]
 [73 28  4 60]
 [61 98 12 70]
 [81 38 26 46]
 [98  6 23 29]]


In [18]:
print(np.argmax(b, axis=0)) # col = 0

[5 3 0 1]


In [19]:
print(np.argmax(b, axis=1)) # row = 1

[1 0 0 1 0 0]


**np.argmin :**
- give the min number index

In [20]:
print(e)
print(np.argmin(e))

[1 2 3 3 4 4 5 5 6 6]
0


In [21]:
print(np.argmin(b, axis=0))

[0 5 2 5]


In [22]:
print(np.argmin(b, axis=1))

[0 2 2 2 2 1]


**np.cumsum :**
- numpy.cumsum() function is used when we want to compute the **cumulative sum of array elements over a given axis.**
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [23]:
# Ex.1D
print(a)
print('cumilative sum : ',np.cumsum(a))

[32 40 41 39 17 16 63 58 14 13  8 32  3  5 14]
cumilative sum :  [ 32  72 113 152 169 185 248 306 320 333 341 373 376 381 395]


In [24]:
# Ex.2D
print(b)

[[30 90 61 32]
 [96 78 26 73]
 [73 28  4 60]
 [61 98 12 70]
 [81 38 26 46]
 [98  6 23 29]]


In [25]:
print(np.cumsum(b))

[  30  120  181  213  309  387  413  486  559  587  591  651  712  810
  822  892  973 1011 1037 1083 1181 1187 1210 1239]


In [26]:
print(np.cumsum(b,axis=0)) # 1 = row

[[ 30  90  61  32]
 [126 168  87 105]
 [199 196  91 165]
 [260 294 103 235]
 [341 332 129 281]
 [439 338 152 310]]


In [27]:
print(np.cumsum(b,axis=1)) # 0 = col

[[ 30 120 181 213]
 [ 96 174 200 273]
 [ 73 101 105 165]
 [ 61 159 171 241]
 [ 81 119 145 191]
 [ 98 104 127 156]]


**np.cumprod :**
- numpy.cumprod() function is used multiplication

In [28]:
print(e)
print(np.cumprod(e))

[1 2 3 3 4 4 5 5 6 6]
[     1      2      6     18     72    288   1440   7200  43200 259200]


In [29]:
print(np.cumprod(b))

[         30        2700      164700     5270400   505958400   810049536
  -413548544  -124272640  -481968128  -610205696  1854144512  -420478976
   120586240 -1067450368    75497472   989855744 -1426063360  1644167168
  -201326592  -671088640 -1342177280   536870912  -536870912  1610612736]


**np.percentile :**
- numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
- **formula :** p = (n/N)*100
    - p : percentile
    - n : Number of values fall under(below) 'x' 
    - N : Total count of population

In [39]:
print(e)

[1 2 3 3 4 4 5 5 6 6]


In [36]:
print(np.percentile(e,0))
print(np.percentile(e,50))
print(np.percentile(e,100))

1.0
4.0
6.0


**np.histogram:**
- Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution for the graphical form.
- https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [48]:
#Ex.
ee = np.array([11,53,28,50,38,37,94,92,5,30,68,9,78,2,21])
print(ee)

[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]


In [50]:
print(np.histogram(ee,bins=[0,10,20,30,40,50,60,70,80,90,100]))

(array([3, 1, 2, 3, 0, 2, 1, 1, 0, 2], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [ ]:
**np.corrcoef :**
- Return Pearson product-moment correlation coefficients.
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [51]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]
